const NEW_FOLLOWER = "NEW_FOLLOWER";
const NEW_PUBLICATION = "NEW_PUBLICATION";
const NEW_COMMENT = "NEW_COMMENT";
const NEW_LIKE = "NEW_LIKE";

module.exports = {
  NEW_FOLLOWER,
  NEW_PUBLICATION,
  NEW_COMMENT,
  NEW_LIKE,
};
